# SITE CONFIGURATION
title: Baseball Storming  # your site title!
author: JaeHyeon Lee # You :P
description: 야구, 통계, 머신러닝을 결합해보자 # Meta description of Homepage
baseurl: # the subpath of your site, e.g. /blog
url: "https://skz2356.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: JaeHyeon Lee
  links:
    - https://www.instagram.com/jaehyeon6141
    - https://www.facebook.com/bsLJH
    - https://github.com/skz2356

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Baseball', link: '/baseball'}
  - {name: 'Column', link: '/column'}
  - {name: 'DataMining ', link: '/datamining'}

tagline: >
  야구에 대한 끊임없는 생각

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/_lg.jpg

email: skz2356@naver.com # email for form submission

facebook_username: bsLJH # replace with your_twitter_username or comment to remove link from footer
github_username: skz2356 # replace with your_github_username or comment to remove link from footer
instagram_username: jaehyeon6141 # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: BSLJH # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-# Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
